#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 按钮相关配置
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define CTRL_BUTTON_GPIO P4

// 电源相关配置
#define PWR_HOLD_GPIO P5
#define PWR_CHARGE_DONE_GPIO P6
#define PWR_CHARGING_GPIO P7
#define BATTERY_ADC_GPIO GPIO_NUM_10 // 电池电压检测ADC1_CH9

// LED相关配置
#define LED_RED_GPIO P2
#define LED_GREEN_GPIO P3

// 音频相关配置
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE true

#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2 // I2C时钟线
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1 // I2C数据线

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13 // 主时钟
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14 // 位时钟
#define AUDIO_I2S_GPIO_WS GPIO_NUM_17   // 帧时钟
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_18 // 数据输出（扬声器）
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_21  // 数据输入（麦克风）

#define AUDIO_CODEC_PA_PIN P1 // NS4150B功放使能引脚
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82

// LCD 屏幕相关配置
#define BOARD_LCD_TYPE LCD_TYPE_WLK_1_8_INCH // LCD 屏幕类型

#define DISPLAY_WIDTH 360
#define DISPLAY_HEIGHT 360
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define QSPI_LCD_H_RES (360)
#define QSPI_LCD_V_RES (360)
#define QSPI_LCD_BIT_PER_PIXEL (16)

#define QSPI_PIN_NUM_LCD_BL P0
#define QSPI_PIN_NUM_LCD_SCLK GPIO_NUM_6
#define QSPI_PIN_NUM_LCD_CS GPIO_NUM_42
#define QSPI_PIN_NUM_LCD_DATA0 GPIO_NUM_7
#define QSPI_PIN_NUM_LCD_DATA1 GPIO_NUM_41
#define QSPI_PIN_NUM_LCD_DATA2 GPIO_NUM_8
#define QSPI_PIN_NUM_LCD_DATA3 GPIO_NUM_40
#define QSPI_PIN_NUM_LCD_RST GPIO_NUM_4

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define TP_PORT (I2C_NUM_1)
#define TP_PIN_NUM_RST (GPIO_NUM_N4)
#define TP_PIN_NUM_INT (GPIO_NUM_5)

#define DISPLAY_BACKLIGHT_PIN QSPI_PIN_NUM_LCD_BL
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif