#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// I2C相关配置
#define I2C_SCL_GPIO GPIO_NUM_2 // I2C 时钟线
#define I2C_SDA_GPIO GPIO_NUM_1 // I2C 数据线
#define I2C_INT_GPIO GPIO_NUM_5

// 按钮相关配置
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define CTRL_BUTTON_GPIO TCA6408A_GPIO_P4 // TCA6408A P4 - 控制按键

// 电源相关配置（通过 TCA6408A IO 扩展器）
#define TCA6408A_PWR_HOLD_GPIO TCA6408A_GPIO_P5        // TCA6408A P5 - 电源保持
#define TCA6408A_PWR_CHARGE_DONE_GPIO TCA6408A_GPIO_P6 // TCA6408A P6 - 充电完成检测
#define TCA6408A_PWR_CHARGING_GPIO TCA6408A_GPIO_P7    // TCA6408A P7 - 充电中检测
// 原生 GPIO 电源引脚别名（用于兼容旧代码）
#define PWR_HOLD_GPIO TCA6408A_PWR_HOLD_GPIO
#define PWR_CHARGE_DONE_GPIO TCA6408A_PWR_CHARGE_DONE_GPIO
#define PWR_CHARGING_GPIO TCA6408A_PWR_CHARGING_GPIO

// 电池电压检测 ADC1_CH9
#define BATTERY_ADC_GPIO GPIO_NUM_10

// LED 相关配置（通过 TCA6408A IO 扩展器）
#define TCA6408A_LED_RED_GPIO TCA6408A_GPIO_P2   // TCA6408A P2 - 红色 LED
#define TCA6408A_LED_GREEN_GPIO TCA6408A_GPIO_P3 // TCA6408A P3 - 绿色 LED
// 原生 GPIO LED 引脚别名（用于兼容旧代码）
#define LED_RED_GPIO TCA6408A_LED_RED_GPIO
#define LED_GREEN_GPIO TCA6408A_LED_GREEN_GPIO

// 音频相关配置
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13 // 主时钟
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14 // 位时钟
#define AUDIO_I2S_GPIO_WS GPIO_NUM_17   // 帧时钟
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_18 // 数据输出（扬声器）
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_21  // 数据输入（麦克风）

#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC
#define TCA6408A_AUDIO_CODEC_PA_PIN TCA6408A_GPIO_P1 // TCA6408A P1 - NS4150B 功放使能引脚
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

// LCD 屏幕相关配置
#define BOARD_LCD_TYPE LCD_TYPE_WLK_1_8_INCH // LCD 屏幕类型

#define DISPLAY_WIDTH 360
#define DISPLAY_HEIGHT 360
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define QSPI_LCD_H_RES (360)
#define QSPI_LCD_V_RES (360)
#define QSPI_LCD_BIT_PER_PIXEL (16)

#define QSPI_PIN_NUM_LCD_BL TCA6408A_GPIO_P0 // TCA6408A P0 - LCD 背光控制
#define QSPI_PIN_NUM_LCD_SCLK GPIO_NUM_6
#define QSPI_PIN_NUM_LCD_CS GPIO_NUM_42
#define QSPI_PIN_NUM_LCD_DATA0 GPIO_NUM_7
#define QSPI_PIN_NUM_LCD_DATA1 GPIO_NUM_41
#define QSPI_PIN_NUM_LCD_DATA2 GPIO_NUM_8
#define QSPI_PIN_NUM_LCD_DATA3 GPIO_NUM_40
#define QSPI_PIN_NUM_LCD_RST GPIO_NUM_4

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define TP_PORT (I2C_NUM_1)
#define TP_PIN_NUM_RST (GPIO_NUM_N4)
#define TP_PIN_NUM_INT (GPIO_NUM_5)

#define DISPLAY_BACKLIGHT_PIN QSPI_PIN_NUM_LCD_BL
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif