#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 按钮相关配置
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define CTRL_BUTTON_GPIO GPIO_NUM_18

// 电源相关配置
#define PWR_HOLD_GPIO GPIO_NUM_39
#define PWR_CHARGE_DONE_GPIO GPIO_NUM_21
#define PWR_CHARGING_GPIO GPIO_NUM_15
#define BATTERY_ADC_GPIO GPIO_NUM_10 // 电池电压检测ADC1_CH9

// LED相关配置
#define LED_RED_GPIO GPIO_NUM_48
#define LED_GREEN_GPIO GPIO_NUM_47

// 音频相关配置
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE true

#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_11 // I2C时钟线
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_12 // I2C数据线

// #define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38 // 主时钟
// #define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14 // 位时钟
// #define AUDIO_I2S_GPIO_WS GPIO_NUM_16   // 帧时钟
// #define AUDIO_I2S_GPIO_DOUT GPIO_NUM_13 // 数据输出（扬声器）
// #define AUDIO_I2S_GPIO_DIN GPIO_NUM_17  // 数据输入（麦克风）

// #define AUDIO_CODEC_PA_PIN GPIO_NUM_41                    // NS4150B功放使能引脚
// #define AUDIO_CODEC_ES8389_ADDR ES8389_CODEC_DEFAULT_ADDR // ES8389默认I2C地址

// LCD 屏幕相关配置
#define BOARD_LCD_TYPE DISPLAY_TYPE_JYC_0_71_INCH // LCD 屏幕类型

#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 160
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_X_1 false
#define DISPLAY_MIRROR_X_2 true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_ROTATION 0

#define LCD_H_RES (160)
#define LCD_V_RES (160)
#define LCD_BIT_PER_PIXEL (16)
#define LCD_HOST SPI2_HOST

//Nano3.4初代拓展板
// #define DISPLAY_GC9D01_BL_GPIO GPIO_NUM_40    // Backlight
// #define DISPLAY_SPI_MOSI_GPIO GPIO_NUM_6
// #define DISPLAY_SPI_SCLK_GPIO GPIO_NUM_5   // SCL
// #define DISPLAY_GC9D01_RESET_GPIO GPIO_NUM_4 // RST
// #define DISPLAY_SPI_CS_1_GPIO GPIO_NUM_7    // CS
// #define DISPLAY_SPI_CS_2_GPIO GPIO_NUM_8 
// #define DISPLAY_GC9D01_DC_GPIO GPIO_NUM_9   // DC

//Nano3.4Toy拓展板
// #define DISPLAY_SPI_MOSI_GPIO GPIO_NUM_8
// #define DISPLAY_SPI_SCLK_GPIO GPIO_NUM_6   // SCL
// #define DISPLAY_SPI_CS_1_GPIO GPIO_NUM_4    // CS1
// #define DISPLAY_SPI_CS_2_GPIO GPIO_NUM_5    // CS2
// #define DISPLAY_GC9D01_DC_GPIO GPIO_NUM_3   // DC
// #define DISPLAY_GC9D01_RESET_GPIO GPIO_NUM_7 // RST
// #define DISPLAY_GC9D01_BL_GPIO GPIO_NUM_1 

//Nano2.1拓展板
#define DISPLAY_SPI_MOSI_GPIO GPIO_NUM_4
#define DISPLAY_SPI_SCLK_GPIO GPIO_NUM_5   // SCL
#define DISPLAY_SPI_CS_1_GPIO GPIO_NUM_6    // CS1
#define DISPLAY_SPI_CS_2_GPIO GPIO_NUM_44    // CS2
#define DISPLAY_GC9D01_DC_GPIO GPIO_NUM_7   // DC
#define DISPLAY_GC9D01_RESET_GPIO GPIO_NUM_8 // RST
#define DISPLAY_GC9D01_BL_GPIO GPIO_NUM_43 

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_9 // 主时钟
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14 // 位时钟
#define AUDIO_I2S_GPIO_WS GPIO_NUM_16   // 帧时钟
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_13 // 数据输出（扬声器）
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_17  // 数据输入（麦克风）

#define AUDIO_CODEC_PA_PIN GPIO_NUM_38                    // NS4150B功放使能引脚
#define AUDIO_CODEC_ES8389_ADDR ES8389_CODEC_DEFAULT_ADDR // ES8389默认I2C地址

#endif