#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// I2C相关配置
#define I2C_SCL_GPIO GPIO_NUM_2 // I2C 时钟线
#define I2C_SDA_GPIO GPIO_NUM_1 // I2C 数据线
#define I2C_INT_GPIO GPIO_NUM_5 // 中断

// TCA6408A 第二个芯片地址（ADDR接VCC）
#define TCA6408A_SECOND_ADDR 0x21

// 按钮相关配置
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define TCA6408A_CTRL_BUTTON_GPIO TCA6408A_GPIO_P4 // TCA6408A P4 - 控制按键

// 电源相关配置（通过 TCA6408A IO 扩展器 - 第一个芯片 0x20）
#define TCA6408A_PWR_HOLD_GPIO TCA6408A_GPIO_P5        // TCA6408A P5 - 电源保持
#define TCA6408A_PWR_CHARGE_DONE_GPIO TCA6408A_GPIO_P6 // TCA6408A P6 - 充电完成检测
#define TCA6408A_PWR_CHARGING_GPIO TCA6408A_GPIO_P7    // TCA6408A P7 - 充电中检测

// 电池电压检测 ADC1_CH9
#define BATTERY_ADC_GPIO GPIO_NUM_10

// LED 相关配置（通过 TCA6408A IO 扩展器 - 第一个芯片 0x20）
#define TCA6408A_LED_GREEN_GPIO TCA6408A_GPIO_P2 // TCA6408A P2 - 绿色 LED
#define TCA6408A_LED_RED_GPIO TCA6408A_GPIO_P3   // TCA6408A P3 - 红色 LED

// 音频相关配置
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13 // 主时钟
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14 // 位时钟
#define AUDIO_I2S_GPIO_WS GPIO_NUM_17   // 帧时钟
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_18 // 数据输出（扬声器）
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_21  // 数据输入（麦克风）

#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC
#define TCA6408A_AUDIO_CODEC_PA_PIN TCA6408A_GPIO_P1 // TCA6408A P1 - NS4150B 功放使能引脚
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

// LCD 屏幕相关配置 (ILI9342C - 4-Wire SPI)
#define BOARD_LCD_TYPE LCD_TYPE_ILI9342_SPI // 确保项目支持此类型，或在代码中硬编码


#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X true  // ILI9342C 通常需要镜像以匹配物理安装
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false


// TCA6408A 第二个芯片（0x21）引脚定义
#define TCA6408A_SECOND_QSPI_PIN_NUM_LCD_BL TCA6408A_GPIO_P4  // TCA6408A P4 - LCD 背光控制
#define TCA6408A_SECOND_LCD_CS_GPIO TCA6408A_GPIO_P2          // TCA6408A P2 - LCD CS
#define TCA6408A_SECOND_VBAT_EN_GPIO TCA6408A_GPIO_P1         // TCA6408A P1 - VBAT EN
#define TCA6408A_SECOND_CAM_PWDN_GPIO TCA6408A_GPIO_P7        // TCA6408A P7 - CAM PWDN

#define SPI_PIN_NUM_LCD_SCLK GPIO_NUM_48   // SCL
#define SPI_PIN_NUM_LCD_MOSI GPIO_NUM_8   // SDA (MOSI)
#define SPI_PIN_NUM_LCD_RST  GPIO_NUM_NC   // RES
#define SPI_PIN_NUM_LCD_DC   GPIO_NUM_9  // 
               

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define TP_PORT (I2C_NUM_1)
#define TP_PIN_NUM_RST (GPIO_NUM_N4)
#define TP_PIN_NUM_INT (GPIO_NUM_5)

#define DISPLAY_BACKLIGHT_PIN TCA6408A_SECOND_QSPI_PIN_NUM_LCD_BL
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false


// GC2145 摄像头引脚配置
#define CAMERA_PIN_PWDN     GPIO_NUM_NC  // 由 TCA6408A 第二个芯片 P7 控制
#define CAMERA_PIN_RESET    GPIO_NUM_NC  // GC2145 没有 RESET 引脚
#define CAMERA_PIN_XCLK     GPIO_NUM_11  // CAM_MCLK

#define CAMERA_PIN_VSYNC    GPIO_NUM_6   // CAM_VSYNC
#define CAMERA_PIN_HREF     GPIO_NUM_7   // CAM_HSYNC
#define CAMERA_PIN_PCLK     GPIO_NUM_45  // CAM_PCLK

// 摄像头数据引脚 D2-D9
#define CAMERA_PIN_D2       GPIO_NUM_41  // CAM_D2 -> D0
#define CAMERA_PIN_D3       GPIO_NUM_38  // CAM_D3 -> D1
#define CAMERA_PIN_D4       GPIO_NUM_4   // CAM_D4 -> D2
#define CAMERA_PIN_D5       GPIO_NUM_40  // CAM_D5 -> D3
#define CAMERA_PIN_D6       GPIO_NUM_42  // CAM_D6 -> D4
#define CAMERA_PIN_D7       GPIO_NUM_16  // CAM_D7 -> D5
#define CAMERA_PIN_D8       GPIO_NUM_12  // CAM_D8 -> D6
#define CAMERA_PIN_D9       GPIO_NUM_15  // CAM_D9 -> D7


// GC2145 I2C 地址
#define GC2145_I2C_ADDR     0x3C

// 摄像头时钟频率
#define CAMERA_XCLK_FREQ_HZ 15000000  // 24MHz

// 舵机引脚配置
#define SERVO_GPIO_1 GPIO_NUM_3  // IO3 - 舵机 PWM 控制引脚
#define SERVO_GPIO_2 GPIO_NUM_39  // IO39 - 第二个舵机（例如：云台垂直）


#endif